### ISSUE TITLE
Script version of some features needed!

### ISSUE THREAD

**Issue by lsvalmont** [MisterHLunaticwraith/MRHMilsimTools#3]
**Arma 3 Version: Latest
**CBA Version: Latest
**ACE3 Version: Latest
**Milsim Tools Version: Latest

**Mods:**
```
- CBA_A3
- ACE3
-MRH Milsim Tools
```

**Description:**
- Not an issue but a request. Right now there is no scripted version of any kind of PDA system for Arma 3. MRHMilsimTools offers features that so many mission makers need and so many players want yet limits its own market and scope by requiring both ACE 3 and a Mod download. Of course given the amount of features it offers a mod version is more than justified but please consider releasing some of its more attractive and sought out features such a the PDA and the Satellite system as stand alone small scripts. Also adding a few more buttons for executing custom code would be awesome to have on the PDA tabs. Thanks

**Steps to reproduce:**
- None. Mod works great we just need a modular script version of some of its core features. 

**Where did the issue occur?**
- Self-Hosted Multiplayer /  Editor (Multiplayer)

**Comment by MisterHLunaticwraith** [comment]
Sorry I've only just seen your post! I understand that people want it in the form of a script but objects REQUIRE a mod to be added in Arma 3. It is of course possible to use scripts to achieve the other parts of the tablet, but honestly I've put so much work and effort in this mod that I don't like the idea of ripping it apart. My policy on the matter is and will always be: You're free to browse "steal" and modify the code on this github for your own personal use, you can even redistribute it (as long as you give me proper credit) but I won't provide assistance (same goes for the satellite mod).
As for the executing code from the tablet, I have projects for a mock up hacking system but you won't be able to execute actual A3 code because it would be a major breach in security for A3!)
