### ISSUE TITLE
permission too:

### ISSUE THREAD

**Issue by YonVclaw** [MisterHLunaticwraith/MRHMilsimTools#8]
May I have permission to include your parachute and halo work in my mission support mod. 

https://steamcommunity.com/sharedfiles/filedetails/?id=1675214293

**Comment by MisterHLunaticwraith** [comment]
The answer is and will always be: Yes you can, I will never forbid it HOWEVER I do not support or endorse any derivative work and will not provide help/ and support for such endeavors. It's also worth noting that the pbo that contains the items and functions you are asking for calls for other functions and dependencies in other pbos of the mod. If you do use some or all of the assets and scripts in your own mod you are required to mention it explicitly in your mod's description on the workshop. (So that users are aware that the mod may conflict with milsim tools)

**Comment by YonVclaw** [comment]
Thank you...
